openapi: 3.2.0
info:
  title: Madhive deactivate audience API
  version: 1.0.0
  description: The Madhive API provides a comprehensive interface for digital advertising clients and services.
servers:
- url: https://api2.madhive.com/api
  description: apigee
tags:
- name: deactivate audience
paths:
  /v1/audiences/{id}:
    delete:
      tags:
      - deactivate audience
      summary: Ability to archive an audience.
      description: Ability to archive an audience. The archived audience will not be removed from any line items, just removed from lists moving forward and will error if applied to new line items.
      operationId: deleteAudienceById
      parameters:
      - name: id
        in: path
        description: audience id
        required: true
        x-oapi-codegen-extra-tags:
          validate: required,min=28,max=28
        schema:
          type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
              examples:
                response:
                  value:
                    id: x72xe8KgZjoFPKgqKjaPPIUyJtBd
                    message: audience deactivated successfully
                    transaction:
                      id: 4af459ff8e1a36b6bb74fb88f1a02477
                      taskId: '14158884487309867565'
        '400':
          $ref: '#/components/responses/400InvalidID'
        '401':
          $ref: '#/components/responses/401Unauthorized'
      security:
      - oauth2: []
components:
  examples:
    401Ex:
      value:
        error: unauthorized
        status: ERROR
        transaction:
          id: 4af459ff8e1a36b6bb74fb88f1a02477
          taskId: '14158884487309867565'
          created: '2030-11-02T15:04:00Z'
    400InvalidID:
      value:
        error: invalid resource id
        status: ERROR
        transaction:
          id: 4af459ff8e1a36b6bb74fb88f1a02477
          taskId: '14158884487309867565'
          created: '2030-11-02T15:04:00Z'
  responses:
    400InvalidID:
      description: Invalid input
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            response:
              $ref: '#/components/examples/400InvalidID'
    401Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            response:
              $ref: '#/components/examples/401Ex'
  schemas:
    Transaction:
      type: object
      x-go-type-skip-optional-pointer: true
      x-omitempty: false
      required:
      - id
      - taskId
      - created
      properties:
        id:
          type: string
          description: trace id
          example: 4af459ff8e1a36b6bb74fb88f1a02477
        taskId:
          type: string
          x-omitempty: true
          description: task id
          example: '14158884487309867565'
        created:
          type: string
          description: 'order created date, format: yyyy-mm-dd hh:mm:ss'
          example: '2030-11-02T15:04:00Z'
    ErrorResponse:
      type: object
      required:
      - transaction
      properties:
        errors:
          type: array
          x-go-type-skip-optional-pointer: true
          items:
            type: string
          description: many error messages
        error:
          type: string
          x-go-type-skip-optional-pointer: true
          description: error message
          example: Unauthorized
        status:
          type: string
          x-go-type-skip-optional-pointer: true
          description: status of the service
          example: ERROR
        transaction:
          $ref: '#/components/schemas/Transaction'
    GenericResponse:
      type: object
      required:
      - id
      - message
      - transaction
      properties:
        id:
          type: string
          description: resource id
          example: 4af459ff8e1a36b6bb74fb88f1a02477
        message:
          type: string
          description: response message
          example: success
        error:
          type: string
          description: error message
          example: unable to process request
        transaction:
          $ref: '#/components/schemas/Transaction'
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://api2.madhive.com/oauth/token
          scopes: {}
    basicAuth:
      type: http
      description: Basic Authentication Not Implemented
      scheme: basic
    bearerAuth:
      type: apiKey
      name: Authorization
      in: header
      description: jwt access token for authentication
