openapi: 3.2.0
info:
  title: Madhive all publisher groups API
  version: 1.0.0
  description: The Madhive API provides a comprehensive interface for digital advertising clients and services.
servers:
- url: https://api2.madhive.com/api
  description: apigee
tags:
- name: all publisher groups
paths:
  /v1/publishergroups:
    get:
      tags:
      - all publisher groups
      summary: Receive the list of publisher groups and their IDs
      description: Receive the list of publisher groups and their IDs.
      operationId: getPublisherGroupsByOrg
      parameters:
      - $ref: '#/components/parameters/X-Cloud-Trace-Context'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PublisherGroupListResponse'
              examples:
                response:
                  value:
                    transaction:
                      id: 4af459ff8e1a36b6bb74fb88f1a02477
                      taskId: '14158884487309867565'
                    publisherGroups:
                    - id: 0X4Ue7ELKvMI6cQaPzZ8evrO0XUx
                      name: my first publisher group
                      mediaType: VIDEO
        '400':
          $ref: '#/components/responses/400InvalidID'
        '401':
          $ref: '#/components/responses/401Unauthorized'
      security:
      - oauth2: []
components:
  responses:
    400InvalidID:
      description: Invalid input
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            response:
              $ref: '#/components/examples/400InvalidID'
    401Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            response:
              $ref: '#/components/examples/401Ex'
  examples:
    401Ex:
      value:
        error: unauthorized
        status: ERROR
        transaction:
          id: 4af459ff8e1a36b6bb74fb88f1a02477
          taskId: '14158884487309867565'
          created: '2030-11-02T15:04:00Z'
    400InvalidID:
      value:
        error: invalid resource id
        status: ERROR
        transaction:
          id: 4af459ff8e1a36b6bb74fb88f1a02477
          taskId: '14158884487309867565'
          created: '2030-11-02T15:04:00Z'
  schemas:
    Transaction:
      type: object
      x-go-type-skip-optional-pointer: true
      x-omitempty: false
      required:
      - id
      - taskId
      - created
      properties:
        id:
          type: string
          description: trace id
          example: 4af459ff8e1a36b6bb74fb88f1a02477
        taskId:
          type: string
          x-omitempty: true
          description: task id
          example: '14158884487309867565'
        created:
          type: string
          description: 'order created date, format: yyyy-mm-dd hh:mm:ss'
          example: '2030-11-02T15:04:00Z'
    ErrorResponse:
      type: object
      required:
      - transaction
      properties:
        errors:
          type: array
          x-go-type-skip-optional-pointer: true
          items:
            type: string
          description: many error messages
        error:
          type: string
          x-go-type-skip-optional-pointer: true
          description: error message
          example: Unauthorized
        status:
          type: string
          x-go-type-skip-optional-pointer: true
          description: status of the service
          example: ERROR
        transaction:
          $ref: '#/components/schemas/Transaction'
    MediaType:
      type: string
      x-isnullable: false
      x-omitempty: true
      x-oapi-codegen-extra-tags:
        validate: required,oneof=NONE VIDEO AUDIO DISPLAY
      example: VIDEO
      enum:
      - NONE
      - VIDEO
      - AUDIO
      - DISPLAY
    PublisherGroupListResponse:
      x-isnullable: false
      type: object
      required:
      - transaction
      - publisherGroups
      properties:
        publisherGroups:
          type: array
          items:
            $ref: '#/components/schemas/PublisherGroupListItem'
          description: list of publisher groups
        transaction:
          $ref: '#/components/schemas/Transaction'
    PublisherGroupListItem:
      type: object
      required:
      - id
      - name
      - mediaType
      properties:
        id:
          type: string
          x-isnullable: false
          x-omitempty: false
          description: madhive publisher group id
          example: HPAKbbHX1IZFeeAh1K7dSogRUvgF
        name:
          type: string
          x-isnullable: false
          x-omitempty: false
          description: publisher group name
          example: my first publisher group
        mediaType:
          $ref: '#/components/schemas/MediaType'
  parameters:
    X-Cloud-Trace-Context:
      name: X-Cloud-Trace-Context
      in: header
      description: gcp trace
      required: false
      schema:
        type: string
        default: 91f9f012dc7c7ffc13604c77f12a8931
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://api2.madhive.com/oauth/token
          scopes: {}
    basicAuth:
      type: http
      description: Basic Authentication Not Implemented
      scheme: basic
    bearerAuth:
      type: apiKey
      name: Authorization
      in: header
      description: jwt access token for authentication
